PUT http://localhost:4000/patients/25706f59-aec7-4fbd-8cbc-946089b289d7
Content-Type: application/json

{
  "name":"Phantom",
  "email":"XYZ@gmail.com",
  "address":"Dehradun",
  "dateOfBirth":"1995-04-05"

}